vim.g.multi_cursor_start_word_key = '<C-s>'
vim.g.multi_cursor_next_key = '<C-s>'
vim.g.multi_cursor_select_all_word_key = '<A-s>'
vim.g.multi_cursor_skip_key = '<C-x>'
vim.g.multi_cursor_quit_key = '<Esc>'
